-- ============================================================
-- Dados de teste — Campeonato do Algarve
-- Gerado automaticamente a partir de clubes_algarve.json (zerozero.pt)
-- ============================================================

-- 1. ESTADIO
INSERT INTO estadio (nome, cidade, capacidade) VALUES
('Estádio de São Luís', 'Faro', 7000),
('Estádio Algarve', 'Faro/Loulé', 30305),
('Estádio Municipal de Albufeira', 'Albufeira', 3500),
('Estádio Municipal de Portimão', 'Portimão', 4961),
('Estádio José Arcanjo', 'Olhão', 5661),
('Estádio Municipal da Nora - Ferreiras', 'Ferreiras - Albufeira', 2000);

-- 2. CLUBE
INSERT INTO clube (nome, cidade, ano_fundacao, id_estadio) VALUES
('Sporting Clube Farense', 'Faro', 1910, (SELECT id_estadio FROM estadio WHERE nome = 'Estádio de São Luís')),
('Louletano Desportos Clube', 'Loulé', 1923, (SELECT id_estadio FROM estadio WHERE nome = 'Estádio Algarve')),
('Imortal Desportivo Clube', 'Albufeira', 1920, (SELECT id_estadio FROM estadio WHERE nome = 'Estádio Municipal de Albufeira')),
('Portimonense Sporting Clube', 'Portimão', 1914, (SELECT id_estadio FROM estadio WHERE nome = 'Estádio Municipal de Portimão')),
('Sporting Clube Olhanense', 'Olhão', 1912, (SELECT id_estadio FROM estadio WHERE nome = 'Estádio José Arcanjo')),
('Futebol Clube de Ferreiras', 'Ferreiras - Albufeira', 1983, (SELECT id_estadio FROM estadio WHERE nome = 'Estádio Municipal da Nora - Ferreiras'));

-- 3. TREINADOR
INSERT INTO treinador (nome, id_clube) VALUES
('José Faria', (SELECT id_clube FROM clube WHERE nome = 'Sporting Clube Farense')),
('Miguel Valença', (SELECT id_clube FROM clube WHERE nome = 'Louletano Desportos Clube')),
('Leandro Palma', (SELECT id_clube FROM clube WHERE nome = 'Imortal Desportivo Clube')),
('Alex Costa', (SELECT id_clube FROM clube WHERE nome = 'Portimonense Sporting Clube')),
('Ivo Soares', (SELECT id_clube FROM clube WHERE nome = 'Sporting Clube Olhanense')),
('Kevin Lemos', (SELECT id_clube FROM clube WHERE nome = 'Futebol Clube de Ferreiras'));

-- 4. JOGADOR
INSERT INTO jogador (nome, data_nascimento, nacionalidade, posicao, numero_camisola, id_clube) VALUES
('Jakob Tannander', '2000-08-10', 'Suécia', 'Guarda Redes', 1, (SELECT id_clube FROM clube WHERE nome = 'Sporting Clube Farense')),
('Fabijan Buntic', '1997-02-24', 'Croácia', 'Guarda Redes', 97, (SELECT id_clube FROM clube WHERE nome = 'Sporting Clube Farense')),
('Kauã Paes', '2006-08-18', 'Brasil', 'Guarda Redes', 50, (SELECT id_clube FROM clube WHERE nome = 'Sporting Clube Farense')),
('Rodrigo Borges', '1998-08-05', 'Portugal', 'Defesa Central', 5, (SELECT id_clube FROM clube WHERE nome = 'Sporting Clube Farense')),
('Bernardo Antunes', '2004-06-09', 'Portugal', 'Defesa Central', 36, (SELECT id_clube FROM clube WHERE nome = 'Sporting Clube Farense')),
('Dário Miranda', '2003-01-13', 'Portugal', 'Defesa Direito', 45, (SELECT id_clube FROM clube WHERE nome = 'Sporting Clube Farense')),
('Alex Pinto', '1998-07-08', 'Portugal', 'Defesa Direito', 78, (SELECT id_clube FROM clube WHERE nome = 'Sporting Clube Farense')),
('Lucas D’Agrella', '2005-03-26', 'Portugal', 'Defesa Central', 3, (SELECT id_clube FROM clube WHERE nome = 'Sporting Clube Farense')),
('Gonçalo Silva', '1991-06-04', 'Portugal', 'Defesa Central', 37, (SELECT id_clube FROM clube WHERE nome = 'Sporting Clube Farense')),
('Nermin Zolotic', '1993-07-07', 'Bósnia e Herzegovina', 'Defesa Central', 44, (SELECT id_clube FROM clube WHERE nome = 'Sporting Clube Farense')),
('Derick Poloni', '1993-09-01', 'Brasil', 'Defesa Esquerdo', 6, (SELECT id_clube FROM clube WHERE nome = 'Sporting Clube Farense')),
('Toni Herrero', '2001-05-12', 'Espanha', 'Defesa Esquerdo', 22, (SELECT id_clube FROM clube WHERE nome = 'Sporting Clube Farense')),
('Sarpreet Singh', '1999-02-20', 'Nova Zelândia', 'Médio Ofensivo', 10, (SELECT id_clube FROM clube WHERE nome = 'Sporting Clube Farense')),
('Cláudio Falcão', '1994-07-03', 'Brasil', 'Médio Defensivo', 29, (SELECT id_clube FROM clube WHERE nome = 'Sporting Clube Farense')),
('Miguel Menino', '2003-01-10', 'Portugal', 'Médio Centro', 8, (SELECT id_clube FROM clube WHERE nome = 'Sporting Clube Farense')),
('Joseph Nduquidi', '2004-10-31', 'França', 'Médio Centro', 15, (SELECT id_clube FROM clube WHERE nome = 'Sporting Clube Farense')),
('Rafael Teixeira', '2006-01-18', 'Portugal', 'Médio Centro', 88, (SELECT id_clube FROM clube WHERE nome = 'Sporting Clube Farense')),
('Mattheus Oliveira', '1994-07-07', 'Brasil', 'Médio Ofensivo', 27, (SELECT id_clube FROM clube WHERE nome = 'Sporting Clube Farense')),
('Nélson Oliveira', '1991-08-08', 'Portugal', 'Ponta de Lança', 11, (SELECT id_clube FROM clube WHERE nome = 'Sporting Clube Farense')),
('João Resende', '2003-03-26', 'Portugal', 'Extremo Direito', 7, (SELECT id_clube FROM clube WHERE nome = 'Sporting Clube Farense')),
('André Candeias', '2003-01-20', 'Portugal', 'Extremo Direito', 17, (SELECT id_clube FROM clube WHERE nome = 'Sporting Clube Farense')),
('João Gastão', '2006-07-22', 'Angola', 'Extremo Direito', 89, (SELECT id_clube FROM clube WHERE nome = 'Sporting Clube Farense')),
('Gabriel Barbosa', '1999-03-17', 'Brasil', 'Ponta de Lança', 9, (SELECT id_clube FROM clube WHERE nome = 'Sporting Clube Farense')),
('Cuba', '2003-04-16', 'Portugal', 'Ponta de Lança', 18, (SELECT id_clube FROM clube WHERE nome = 'Sporting Clube Farense')),
('Leonardo Oliveira', '2005-02-08', 'Suécia', 'Ponta de Lança', 19, (SELECT id_clube FROM clube WHERE nome = 'Sporting Clube Farense')),
('Enrico', '2006-02-15', 'Brasil', 'Ponta de Lança', 32, (SELECT id_clube FROM clube WHERE nome = 'Sporting Clube Farense')),
('Victor Barbara', '2004-07-19', 'Brasil', 'Extremo Esquerdo', 70, (SELECT id_clube FROM clube WHERE nome = 'Sporting Clube Farense')),
('Gustavo Daris', '2002-06-03', 'Brasil', 'Guarda Redes', 1, (SELECT id_clube FROM clube WHERE nome = 'Louletano Desportos Clube')),
('João Farrajota', '2006-05-04', 'Portugal', 'Guarda Redes', 13, (SELECT id_clube FROM clube WHERE nome = 'Louletano Desportos Clube')),
('Marcão', '2000-04-19', 'Brasil', 'Guarda Redes', 71, (SELECT id_clube FROM clube WHERE nome = 'Louletano Desportos Clube')),
('Tiago Correia', '1994-10-30', 'Portugal', 'Defesa Central', 3, (SELECT id_clube FROM clube WHERE nome = 'Louletano Desportos Clube')),
('Luca van der Gaag', '2001-07-19', 'Países Baixos', 'Defesa Central', 14, (SELECT id_clube FROM clube WHERE nome = 'Louletano Desportos Clube')),
('David Martins', '2000-06-10', 'Portugal', 'Defesa Central', 18, (SELECT id_clube FROM clube WHERE nome = 'Louletano Desportos Clube')),
('Elvis Mendes', '1997-05-08', 'Cabo Verde', 'Defesa Esquerdo', 97, (SELECT id_clube FROM clube WHERE nome = 'Louletano Desportos Clube')),
('Rodrigo Teixeira', '2005-08-17', 'Portugal', 'Defesa Direito', 29, (SELECT id_clube FROM clube WHERE nome = 'Louletano Desportos Clube')),
('Gabriel Passos', '2002-04-19', 'Brasil', 'Defesa Central', 12, (SELECT id_clube FROM clube WHERE nome = 'Louletano Desportos Clube')),
('Martim Cruz', '2004-05-02', 'Portugal', 'Defesa Esquerdo', 21, (SELECT id_clube FROM clube WHERE nome = 'Louletano Desportos Clube')),
('Tomás Vilela', '2004-03-16', 'Portugal', 'Médio Centro', 6, (SELECT id_clube FROM clube WHERE nome = 'Louletano Desportos Clube')),
('Sander Ramires', '2001-03-14', 'Brasil', 'Médio Ofensivo', 8, (SELECT id_clube FROM clube WHERE nome = 'Louletano Desportos Clube')),
('Vítor Gonçalves', '1992-03-29', 'Portugal', 'Médio Centro', 10, (SELECT id_clube FROM clube WHERE nome = 'Louletano Desportos Clube')),
('Miguel Laginha', '2006-05-29', 'Portugal', 'Médio Defensivo', 88, (SELECT id_clube FROM clube WHERE nome = 'Louletano Desportos Clube')),
('Dedé', '2006-03-09', 'Brasil', 'Médio Centro', 65, (SELECT id_clube FROM clube WHERE nome = 'Louletano Desportos Clube')),
('Yan Marinho', '2004-03-24', 'Brasil', 'Médio Ofensivo', 17, (SELECT id_clube FROM clube WHERE nome = 'Louletano Desportos Clube')),
('Tiago Sousa', '2002-11-14', 'Portugal', 'Médio Ofensivo', 19, (SELECT id_clube FROM clube WHERE nome = 'Louletano Desportos Clube')),
('Adair Kandala', '2005-04-19', 'Angola', 'Extremo Direito', 11, (SELECT id_clube FROM clube WHERE nome = 'Louletano Desportos Clube')),
('Daniel Paulino', '2004-04-16', 'Brasil', 'Ponta de Lança', 23, (SELECT id_clube FROM clube WHERE nome = 'Louletano Desportos Clube')),
('Alexandre Dias', '2007-04-14', 'Portugal', 'Médio Defensivo', 87, (SELECT id_clube FROM clube WHERE nome = 'Louletano Desportos Clube')),
('Diogo Teixeira', '2004-06-12', 'Portugal', 'Ponta de Lança', 90, (SELECT id_clube FROM clube WHERE nome = 'Louletano Desportos Clube')),
('Nuno Martelo', '2003-04-10', 'Portugal', 'Extremo Direito', 27, (SELECT id_clube FROM clube WHERE nome = 'Louletano Desportos Clube')),
('Rodrigo Vilela', '1995-03-15', 'Portugal', 'Extremo Esquerdo', 7, (SELECT id_clube FROM clube WHERE nome = 'Louletano Desportos Clube')),
('Gonçalo Teixeira', '1999-11-24', 'Portugal', 'Extremo Esquerdo', 9, (SELECT id_clube FROM clube WHERE nome = 'Louletano Desportos Clube')),
('David Inácio', '2002-12-23', 'Portugal', 'Guarda Redes', 23, (SELECT id_clube FROM clube WHERE nome = 'Imortal Desportivo Clube')),
('Martim Botão', '2006-07-20', 'Portugal', 'Guarda Redes', 99, (SELECT id_clube FROM clube WHERE nome = 'Imortal Desportivo Clube')),
('Rodrigo Salvador', '2005-03-29', 'Portugal', 'Defesa Central', 3, (SELECT id_clube FROM clube WHERE nome = 'Imortal Desportivo Clube')),
('Tiago Caveira', '2000-07-27', 'Brasil', 'Defesa Central', 5, (SELECT id_clube FROM clube WHERE nome = 'Imortal Desportivo Clube')),
('Welson Lopes', '2000-04-08', 'Cabo Verde', 'Defesa Central', 20, (SELECT id_clube FROM clube WHERE nome = 'Imortal Desportivo Clube')),
('Rafael Floro', '1994-01-19', 'Portugal', 'Defesa Esquerdo', 24, (SELECT id_clube FROM clube WHERE nome = 'Imortal Desportivo Clube')),
('Heder Pina', '2002-12-15', 'Cabo Verde', 'Defesa', 79, (SELECT id_clube FROM clube WHERE nome = 'Imortal Desportivo Clube')),
('Luis Silveira', '2005-10-29', 'Brasil', 'Defesa Esquerdo', 88, (SELECT id_clube FROM clube WHERE nome = 'Imortal Desportivo Clube')),
('Diego Prates', '1997-05-14', 'Brasil', 'Médio', 2, (SELECT id_clube FROM clube WHERE nome = 'Imortal Desportivo Clube')),
('Thomas', '1997-09-21', 'Brasil', 'Médio Defensivo', 6, (SELECT id_clube FROM clube WHERE nome = 'Imortal Desportivo Clube')),
('José Coelho', '2000-12-24', 'Portugal', 'Médio', 7, (SELECT id_clube FROM clube WHERE nome = 'Imortal Desportivo Clube')),
('Mica Silva', '1993-03-16', 'Portugal', 'Médio Centro', 19, (SELECT id_clube FROM clube WHERE nome = 'Imortal Desportivo Clube')),
('Rafael Baião', '2001-04-06', 'Portugal', 'Médio Ofensivo', 22, (SELECT id_clube FROM clube WHERE nome = 'Imortal Desportivo Clube')),
('Rodrigo Rodas Silva', '2003-04-11', 'Portugal', 'Médio', 60, (SELECT id_clube FROM clube WHERE nome = 'Imortal Desportivo Clube')),
('Leandro Pimenta', '1990-07-09', 'Portugal', 'Médio Centro', 77, (SELECT id_clube FROM clube WHERE nome = 'Imortal Desportivo Clube')),
('Mamade Fernandes', '2003-02-20', 'Guiné-Bissau', 'Médio Defensivo', 80, (SELECT id_clube FROM clube WHERE nome = 'Imortal Desportivo Clube')),
('Walter Alves', '2003-04-19', 'Brasil', 'Extremo Esquerdo', 10, (SELECT id_clube FROM clube WHERE nome = 'Imortal Desportivo Clube')),
('Diogo Cabral', '2004-07-02', 'Portugal', 'Ponta de Lança', 11, (SELECT id_clube FROM clube WHERE nome = 'Imortal Desportivo Clube')),
('Diogo Silva', '2007-08-18', 'Portugal', 'Avançado', 9, (SELECT id_clube FROM clube WHERE nome = 'Imortal Desportivo Clube')),
('Marocas', '1988-02-17', 'Portugal', 'Ponta de Lança', 21, (SELECT id_clube FROM clube WHERE nome = 'Imortal Desportivo Clube')),
('Ruca', '2001-08-12', 'Portugal', 'Extremo Esquerdo', 50, (SELECT id_clube FROM clube WHERE nome = 'Imortal Desportivo Clube')),
('Dudu', '1999-02-10', 'Alemanha', 'Guarda Redes', 1, (SELECT id_clube FROM clube WHERE nome = 'Portimonense Sporting Clube')),
('Sébastien Cibois', '1998-03-02', 'França', 'Guarda Redes', 23, (SELECT id_clube FROM clube WHERE nome = 'Portimonense Sporting Clube')),
('Wellington Santana', '1997-07-20', 'Brasil', 'Guarda Redes', 65, (SELECT id_clube FROM clube WHERE nome = 'Portimonense Sporting Clube')),
('Lourenço', '2007-05-26', 'Portugal', 'Guarda Redes', 44, (SELECT id_clube FROM clube WHERE nome = 'Portimonense Sporting Clube')),
('Georgii Tunguliiadi', '2004-10-03', 'Rússia', 'Defesa Central', 5, (SELECT id_clube FROM clube WHERE nome = 'Portimonense Sporting Clube')),
('Edney Silva', '2004-07-26', 'Brasil', 'Defesa Direito', 2, (SELECT id_clube FROM clube WHERE nome = 'Portimonense Sporting Clube')),
('Jarleysom', '2004-04-15', 'Brasil', 'Defesa Central', 3, (SELECT id_clube FROM clube WHERE nome = 'Portimonense Sporting Clube')),
('Italo Cabelinho', '2004-02-27', 'Brasil', 'Defesa Central', 4, (SELECT id_clube FROM clube WHERE nome = 'Portimonense Sporting Clube')),
('Samy', '1999-10-20', 'Angola', 'Defesa Central', 6, (SELECT id_clube FROM clube WHERE nome = 'Portimonense Sporting Clube')),
('Marlon Júnior', '2005-08-25', 'Portugal', 'Defesa Central', 73, (SELECT id_clube FROM clube WHERE nome = 'Portimonense Sporting Clube')),
('João Reis', '1992-06-24', 'Portugal', 'Defesa Esquerdo', 17, (SELECT id_clube FROM clube WHERE nome = 'Portimonense Sporting Clube')),
('Thauan Lara', '2004-01-22', 'Brasil', 'Defesa Esquerdo', 36, (SELECT id_clube FROM clube WHERE nome = 'Portimonense Sporting Clube')),
('João Casimiro', '2005-11-16', 'Portugal', 'Médio Centro', 8, (SELECT id_clube FROM clube WHERE nome = 'Portimonense Sporting Clube')),
('Yago Gonçalves', '2006-02-05', 'Brasil', 'Médio Defensivo', 81, (SELECT id_clube FROM clube WHERE nome = 'Portimonense Sporting Clube')),
('Jader', '2003-07-24', 'Brasil', 'Médio Ofensivo', 88, (SELECT id_clube FROM clube WHERE nome = 'Portimonense Sporting Clube')),
('Samuel Yépié Yépié', '2002-02-10', 'França', 'Médio', 9, (SELECT id_clube FROM clube WHERE nome = 'Portimonense Sporting Clube')),
('Wermeson', '2001-02-16', 'Brasil', 'Médio Ofensivo', 38, (SELECT id_clube FROM clube WHERE nome = 'Portimonense Sporting Clube')),
('Favero', '2003-07-16', 'Brasil', 'Médio Defensivo', 80, (SELECT id_clube FROM clube WHERE nome = 'Portimonense Sporting Clube')),
('Xavier', '2000-03-02', 'Brasil', 'Médio Defensivo', 15, (SELECT id_clube FROM clube WHERE nome = 'Portimonense Sporting Clube')),
('Yanis da Rocha', '2004-05-10', 'Portugal', 'Médio Defensivo', 21, (SELECT id_clube FROM clube WHERE nome = 'Portimonense Sporting Clube')),
('Caleb Okerere', '2007-04-01', 'Nigéria', 'Médio Defensivo', 20, (SELECT id_clube FROM clube WHERE nome = 'Portimonense Sporting Clube')),
('Ericson', '2003-08-17', 'Brasil', 'Avançado', 25, (SELECT id_clube FROM clube WHERE nome = 'Portimonense Sporting Clube')),
('João Mendes', '2005-01-25', 'Brasil', 'Extremo Direito', 77, (SELECT id_clube FROM clube WHERE nome = 'Portimonense Sporting Clube')),
('Paulinho Campos', '1999-08-26', 'Portugal', 'Ponta de Lança', 79, (SELECT id_clube FROM clube WHERE nome = 'Portimonense Sporting Clube')),
('Fortunato', '2005-11-18', 'Brasil', 'Extremo Direito', 30, (SELECT id_clube FROM clube WHERE nome = 'Portimonense Sporting Clube')),
('Tiago Mamede', '2002-03-18', 'Portugal', 'Extremo Direito', 18, (SELECT id_clube FROM clube WHERE nome = 'Portimonense Sporting Clube')),
('Midana Cassamá', '2002-08-18', 'Guiné-Bissau', 'Ponta de Lança', 19, (SELECT id_clube FROM clube WHERE nome = 'Portimonense Sporting Clube')),
('Welinton Júnior', '1993-06-08', 'Brasil', 'Ponta de Lança', 93, (SELECT id_clube FROM clube WHERE nome = 'Portimonense Sporting Clube')),
('Danio Djassi', '2006-09-21', 'Guiné-Bissau', 'Extremo Esquerdo', 7, (SELECT id_clube FROM clube WHERE nome = 'Portimonense Sporting Clube')),
('Shoya Nakajima', '1994-08-23', 'Japão', 'Extremo Esquerdo', 10, (SELECT id_clube FROM clube WHERE nome = 'Portimonense Sporting Clube')),
('Diogo Cabral', '2003-06-01', 'Portugal', 'Extremo Esquerdo', 11, (SELECT id_clube FROM clube WHERE nome = 'Portimonense Sporting Clube')),
('Gonçalo Águas', '2003-10-13', 'Portugal', 'Extremo Esquerdo', 70, (SELECT id_clube FROM clube WHERE nome = 'Portimonense Sporting Clube')),
('Leo Santos', '1999-01-07', 'Portugal', 'Guarda Redes', 23, (SELECT id_clube FROM clube WHERE nome = 'Sporting Clube Olhanense')),
('João Félix', '2003-01-23', 'Portugal', 'Guarda Redes', 45, (SELECT id_clube FROM clube WHERE nome = 'Sporting Clube Olhanense')),
('Pedro Carriço', '2007-10-10', 'Portugal', 'Guarda Redes', 77, (SELECT id_clube FROM clube WHERE nome = 'Sporting Clube Olhanense')),
('Filipe Carmo', '2007-09-04', 'Portugal', 'Guarda Redes', 81, (SELECT id_clube FROM clube WHERE nome = 'Sporting Clube Olhanense')),
('João Azul', '1988-04-17', 'Portugal', 'Guarda Redes', 88, (SELECT id_clube FROM clube WHERE nome = 'Sporting Clube Olhanense')),
('Fabinho', '1998-07-25', 'Portugal', 'Defesa Direito', 13, (SELECT id_clube FROM clube WHERE nome = 'Sporting Clube Olhanense')),
('Gonçalo Martins', '1998-05-29', 'Portugal', 'Defesa Direito', 27, (SELECT id_clube FROM clube WHERE nome = 'Sporting Clube Olhanense')),
('Hugo Matias', '2003-06-17', 'Portugal', 'Defesa Central', 3, (SELECT id_clube FROM clube WHERE nome = 'Sporting Clube Olhanense')),
('Amaro Viana', '1997-02-18', 'Portugal', 'Defesa Central', 4, (SELECT id_clube FROM clube WHERE nome = 'Sporting Clube Olhanense')),
('Aílton Tavares', '1995-05-14', 'Cabo Verde', 'Defesa Central', 6, (SELECT id_clube FROM clube WHERE nome = 'Sporting Clube Olhanense')),
('João Correia', '2000-02-28', 'Portugal', 'Defesa Central', 28, (SELECT id_clube FROM clube WHERE nome = 'Sporting Clube Olhanense')),
('Miguel Pires', '2002-11-16', 'Portugal', 'Defesa Esquerdo', 14, (SELECT id_clube FROM clube WHERE nome = 'Sporting Clube Olhanense')),
('Celsinho', '1996-07-12', 'Portugal', 'Defesa Esquerdo', 47, (SELECT id_clube FROM clube WHERE nome = 'Sporting Clube Olhanense')),
('Jair Brito', '2002-10-18', 'Portugal', 'Defesa Esquerdo', 70, (SELECT id_clube FROM clube WHERE nome = 'Sporting Clube Olhanense')),
('Farouk Mohammed', '2005-01-07', 'Gana', 'Médio', 21, (SELECT id_clube FROM clube WHERE nome = 'Sporting Clube Olhanense')),
('Tomás Cintra', '2005-01-28', 'Portugal', 'Médio Defensivo', 22, (SELECT id_clube FROM clube WHERE nome = 'Sporting Clube Olhanense')),
('Caio Carioca', '2000-03-28', 'Brasil', 'Médio Centro', 16, (SELECT id_clube FROM clube WHERE nome = 'Sporting Clube Olhanense')),
('Zé António', '2004-10-23', 'Portugal', 'Médio Centro', 91, (SELECT id_clube FROM clube WHERE nome = 'Sporting Clube Olhanense')),
('Paulo Forra', '2001-03-17', 'Portugal', 'Médio Ofensivo', 8, (SELECT id_clube FROM clube WHERE nome = 'Sporting Clube Olhanense')),
('David Vieira', '1998-05-13', 'Portugal', 'Médio Ofensivo', 19, (SELECT id_clube FROM clube WHERE nome = 'Sporting Clube Olhanense')),
('Bruno Fernandes', '1994-06-21', 'Brasil', 'Médio Ofensivo', 20, (SELECT id_clube FROM clube WHERE nome = 'Sporting Clube Olhanense')),
('Afonso Calvinho', '2001-01-22', 'Portugal', 'Avançado', 10, (SELECT id_clube FROM clube WHERE nome = 'Sporting Clube Olhanense')),
('Alexandro Bardziy', '2007-09-08', 'Portugal', 'Avançado', 17, (SELECT id_clube FROM clube WHERE nome = 'Sporting Clube Olhanense')),
('Rosário Silva', '1999-01-24', 'Angola', 'Avançado', 30, (SELECT id_clube FROM clube WHERE nome = 'Sporting Clube Olhanense')),
('Daniel Popa', '2001-12-31', 'Portugal', 'Extremo Direito', 80, (SELECT id_clube FROM clube WHERE nome = 'Sporting Clube Olhanense')),
('Victor Nicolatti', '2000-01-22', 'Brasil', 'Ponta de Lança', 9, (SELECT id_clube FROM clube WHERE nome = 'Sporting Clube Olhanense')),
('Juan Nazarit', '2003-03-27', 'Colômbia', 'Ponta de Lança', 11, (SELECT id_clube FROM clube WHERE nome = 'Sporting Clube Olhanense')),
('Tomás Fernandes', '2001-01-26', 'Portugal', 'Extremo Esquerdo', 7, (SELECT id_clube FROM clube WHERE nome = 'Sporting Clube Olhanense')),
('Gustavo Campos', '2006-01-09', 'Portugal', 'Guarda Redes', 1, (SELECT id_clube FROM clube WHERE nome = 'Futebol Clube de Ferreiras')),
('Rafael Correia', '2006-04-30', 'Portugal', 'Guarda Redes', 12, (SELECT id_clube FROM clube WHERE nome = 'Futebol Clube de Ferreiras')),
('Miguel Freitas', '2005-05-04', 'Portugal', 'Guarda Redes', 24, (SELECT id_clube FROM clube WHERE nome = 'Futebol Clube de Ferreiras')),
('Bruno Costa', '1986-08-28', 'Portugal', 'Guarda Redes', 40, (SELECT id_clube FROM clube WHERE nome = 'Futebol Clube de Ferreiras')),
('Tiago Paixão', '2005-05-02', 'Portugal', 'Defesa Central', 17, (SELECT id_clube FROM clube WHERE nome = 'Futebol Clube de Ferreiras')),
('Samuel Ramos', '1994-05-29', 'Brasil', 'Defesa Direito', 2, (SELECT id_clube FROM clube WHERE nome = 'Futebol Clube de Ferreiras')),
('Pakkie Tavares', '2004-08-10', 'Portugal', 'Defesa Direito', 18, (SELECT id_clube FROM clube WHERE nome = 'Futebol Clube de Ferreiras')),
('Luiz Olímpio', '2005-01-05', 'Brasil', 'Defesa Central', 3, (SELECT id_clube FROM clube WHERE nome = 'Futebol Clube de Ferreiras')),
('João Rosa', '1998-06-07', 'Portugal', 'Defesa Central', 22, (SELECT id_clube FROM clube WHERE nome = 'Futebol Clube de Ferreiras')),
('Daniel Custódio', '2006-01-26', 'Portugal', 'Defesa Esquerdo', 5, (SELECT id_clube FROM clube WHERE nome = 'Futebol Clube de Ferreiras')),
('Simão Mestre', '2005-05-14', 'Portugal', 'Defesa Esquerdo', 15, (SELECT id_clube FROM clube WHERE nome = 'Futebol Clube de Ferreiras')),
('Rafael Teixeira', '1998-09-23', 'Portugal', 'Médio Defensivo', 6, (SELECT id_clube FROM clube WHERE nome = 'Futebol Clube de Ferreiras')),
('André Pereira', '2001-08-08', 'Portugal', 'Médio Direito', 23, (SELECT id_clube FROM clube WHERE nome = 'Futebol Clube de Ferreiras')),
('Daniel Cunha', '2007-10-15', 'Portugal', 'Médio Defensivo', 14, (SELECT id_clube FROM clube WHERE nome = 'Futebol Clube de Ferreiras')),
('Tiago Buchinho', '2004-08-16', 'Portugal', 'Médio Defensivo', 16, (SELECT id_clube FROM clube WHERE nome = 'Futebol Clube de Ferreiras')),
('Wilson Quintino', '1996-02-13', 'Portugal', 'Médio Defensivo', 28, (SELECT id_clube FROM clube WHERE nome = 'Futebol Clube de Ferreiras')),
('Nuno Silva', '1989-03-04', 'Portugal', 'Médio Centro', 8, (SELECT id_clube FROM clube WHERE nome = 'Futebol Clube de Ferreiras')),
('Guilherme Martins', '2005-04-27', 'Portugal', 'Médio Centro', 11, (SELECT id_clube FROM clube WHERE nome = 'Futebol Clube de Ferreiras')),
('Tomás Coelho', '2005-04-28', 'Portugal', 'Médio Centro', 25, (SELECT id_clube FROM clube WHERE nome = 'Futebol Clube de Ferreiras')),
('Bernardo Zambujeiro', '2007-05-29', 'Portugal', 'Médio Ofensivo', 27, (SELECT id_clube FROM clube WHERE nome = 'Futebol Clube de Ferreiras')),
('João Tempera', '2007-03-08', 'Portugal', 'Médio Ofensivo', 33, (SELECT id_clube FROM clube WHERE nome = 'Futebol Clube de Ferreiras')),
('Diogo Barreto', '2009-09-21', 'Portugal', 'Extremo Direito', 19, (SELECT id_clube FROM clube WHERE nome = 'Futebol Clube de Ferreiras')),
('Carlos Santos', '2007-11-17', 'Portugal', 'Extremo Direito', 7, (SELECT id_clube FROM clube WHERE nome = 'Futebol Clube de Ferreiras')),
('Aaron Martinez', '2006-12-15', 'Portugal', 'Extremo Direito', 13, (SELECT id_clube FROM clube WHERE nome = 'Futebol Clube de Ferreiras')),
('Vladyslav Prysyazhnyuk', '2006-03-12', 'Portugal', 'Extremo Direito', 30, (SELECT id_clube FROM clube WHERE nome = 'Futebol Clube de Ferreiras')),
('André Chamusca', '1999-11-23', 'Portugal', 'Ponta de Lança', 10, (SELECT id_clube FROM clube WHERE nome = 'Futebol Clube de Ferreiras')),
('Diogo Próspero', '2000-10-14', 'Portugal', 'Ponta de Lança', 20, (SELECT id_clube FROM clube WHERE nome = 'Futebol Clube de Ferreiras')),
('Martim Pacheco', '2006-02-24', 'Portugal', 'Ponta de Lança', 26, (SELECT id_clube FROM clube WHERE nome = 'Futebol Clube de Ferreiras')),
('António Pato', '2005-02-15', 'Portugal', 'Ponta de Lança', 29, (SELECT id_clube FROM clube WHERE nome = 'Futebol Clube de Ferreiras'));
